Iter5
ElizavetaFirst/go-metrics-alerts pull request #1
Opened 2023-11-06 19:28 UTC by ElizavetaFirst

2023-11-07 15:35 UTC, arttet requested changes
Please fix CI

Please read it
https://cbea.ms/git-commit/
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

Please add linters in CI https://github.com/golangci/golangci-lint
Please add the code coverage report in CI https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
Please add gofmt in CI https://github.com/marketplace/actions/check-code-formatting-using-gofmt

2023-11-07 15:35 UTC, arttet commented on Makefile
> +.DEFAULT_GOAL := build
Please avoid duplicate code

2023-11-07 15:35 UTC, arttet commented on cmd/agent/main.go
> +func getEnvDuration(key string, defaultVal time.Duration) time.Duration {
Please move it to another package

2023-11-07 15:35 UTC, arttet commented on cmd/agent/main.go
> +var rootCmd = &cobra.Command{
It shouldn't be in main.cpp

2023-11-07 15:35 UTC, arttet commented on internal/agent/uploader/uploader.go
> +		req, _ := http.NewRequest("POST", "http://"+u.addr+"/update/gauge/"+k+"/"+strconv.FormatFloat(v, 'f', -1, 64), nil)
Please use `format`

2023-11-07 15:35 UTC, arttet commented on internal/server/handler/handler.go
> +	for name, metric := range values {
Please use `strings.Builder`

2023-11-07 15:35 UTC, arttet commented on internal/server/handler/handler_test.go
> +type mockStorage struct{}
It should be an interface

2023-11-07 15:35 UTC, arttet commented on internal/server/storage/storage.go
> +type MemStorage struct {
It should be private

2023-11-07 15:35 UTC, arttet commented on internal/server/storage/storage.go
> +type Metric struct {
It should be in the model package

2023-11-07 15:35 UTC, arttet commented on internal/server/storage/storage.go
> +	Data map[string]Metric
It would be better if you use `sync.map`

2023-11-07 15:35 UTC, arttet commented on internal/server/storage/storage.go
> +import (
Please apply gofmt

2023-11-10 09:12 UTC, ElizavetaFirst commented on internal/server/handler/handler_test.go
> +type mockStorage struct{}
у меня его тогда в функциях не выходит использовать
как я понимаю,нужно структура и интерфейс который она реализует,для использования

2023-11-10 10:01 UTC, closed without merging