Iter13
ElizavetaFirst/go-metrics-alerts pull request #12
Opened 2023-12-19 19:02 UTC by ElizavetaFirst

2023-12-19 19:04 UTC, ElizavetaFirst commented
Тесты проходили, пока я не исправила замечания линтера:(
Все равно решила залить  PR, так как обещала сегодня залить, в ближайшие дни постараюсь посмотреть, что не так.

2023-12-20 22:59 UTC, s-shpak requested changes
1. Я не нашел логики retryable-запросов для агента. Ее можно реализовать при помощи, например, https://github.com/hashicorp/go-retryablehttp
2. Если будешь добавлять линтер, то добавь его уже сейчас - не страшно, если какие-то проблемы не будут поправлены, как мы договаривались, их можно будет доделать на 4-м спринте

2023-12-20 22:59 UTC, s-shpak commented on cmd/server/main.go
> +	/*root.RootCmd.PersistentFlags().StringVarP(&databaseDSN, "databaseDSN", "d",
deadcode. Если хочешь сохранить строку для локального тестирования, то лучше добавь ее в `README.md`

2023-12-20 22:59 UTC, s-shpak commented on cmd/server/root/root.go
> +					fmt.Printf("failed to close the postgres storage %v", err)
Не пользуйся `fmt.Print[f|ln]`, используй пакет логирования для вывода сообщений

2023-12-20 22:59 UTC, s-shpak commented on cmd/server/root/root.go
> +					os.Exit(0)
Не стоит завершать процесс из горутины, ошибку желательно прокинуть наверх, чтобы всегда заверщаться из одного и того же места

2023-12-20 22:59 UTC, s-shpak commented on internal/agent/uploader/uploader.go
> +	updateReqFormat  = "http://%s/update"
Не очень хорошо, что ты разнесла шаблон строки и его заполнение: сложно понять, как правильно использовать шаблон. Это можно решить двумя способами:
1. создать функцию, которая будет заолнять шаблон и возвращать строку
2. использовать шаблон напрямую в `fmt.Sprintf` (если тебе не позволяет это сделать линтер, то обнови его конфигурацию - в текущей этой проблемы быть не должно)

2023-12-20 22:59 UTC, s-shpak commented on internal/agent/uploader/uploader.go
> +		return errors.Wrap(err, cantMarshalJSON)
Здесь аналогичное замечание + удобнее оборачивать ошибки при помощи `fmt.Errorf`

2023-12-20 22:59 UTC, s-shpak commented on internal/agent/uploader/uploader.go
> +			Value: &v,
Если ты указываешь тип в объекте модели, то, кажется, что делать `Value` и `Counter` указателями - лишнее. Про оптимизации мы буем говорить во второй части курса, но можно принять во внимание сейчас, что использование указателей часто снижает производительность программы

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +type TestMetric struct {
deadcode

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +	if err := db.conn.Ping(context.Background()); err != nil {
Мы обсуждали это на последнем вебинаре, но можно делать это сразу для этого спринта: контекст должен приходить извне. Это будет либо контекст запроса, либо корневой (или дочерний от корневого) контекст приложения. Корневой контекст - тот, который ты запускаешь в точке входа программы

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +	return nil // pgxpool.Pool не нужно закрывать
Почему ?

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +func (db *DB) CreateTable(ctx context.Context) error {
Это необходимо делать при помощи миграций

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +	fmt.Println(db.conn.Config().ConnConfig.User)
deadcode или debug-логгирование

2023-12-20 22:59 UTC, s-shpak commented on internal/server/db/db.go
> +type DB struct {
Тебе точно нужна эта обретка ? Почему бы не совместить ее с `*DBStorage` ?

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler.go
> +	value, err := h.Storage.Get(c, &storage.GetOptions{
Здесь лучше возвращать ошибку, которую можно проверить через `errors.Is`, чтобы понять, что `StatusNotFound`

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler.go
>  		c.Status(http.StatusNotFound)
Что если `err != nil`, но не из-за того, что значение не найдено, а по другой причине ?

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler.go
> +	for _, m := range metrics {
Сложный код, лучше упростить. Как это можно сделать (не обязательно использовать все, это просто идеи):
1. switch-case
2. вынести логику разных кейсов в отделные функции
3. сначал проверять ошибочный кейс, если он реализуется выходить раньше, чтобы снизить вложенность кода

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler.go
> +		} else if m.MType == constants.Counter {
А если ни то, ни другое, то эта ошибка, которую можно залогировать

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
Тексты нештатных ошибок (>=500) нельзя отдавать пользователю, т.к. это небезопасно. Но их стоит логировать

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler_test.go
> +func (ms *mockStorage) Update(ctx context.Context, opts *storage.UpdateOptions) error {
Не стоит вручную создавать мок хранилища. Либо генерируй его (на 3 вебинаре обсуждали как), либо испоьзуй in-memory хранилище, оно вполне подходит для тестов

2023-12-20 22:59 UTC, s-shpak commented on internal/server/handler/handler_test.go
> +	/*fakeDB := &db.FakeDB{}
deadcode

2023-12-20 22:59 UTC, s-shpak commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
Это плохой вариант `graceful shutdown`, т.к. он не позволяет штатно завершить работу сервера. Graceful shutdown пока делать не обязательно, но, если очень хочется, посмотри последний вебинар, на нем мы все обсуждали

2023-12-20 22:59 UTC, s-shpak commented on internal/server/storage/dbstorage.go
> +	err = realDB.CreateTable(ctx)
Нужно делать это при помощи миграций (см. 4 вебинар)

2023-12-20 22:59 UTC, s-shpak commented on internal/server/storage/dbstorage.go
> +	if dbs.db == nil {
Мне кажется, что это можно не проверять: если `db` почему-то не проинициализирована, то это критическая ошибка, и в выбрасываемой панике нет ничего страшного (панику можно -- и нужно в рабочем проекте -- поймать выше, но это другая история)

2023-12-20 22:59 UTC, s-shpak commented on internal/server/storage/memstorage.go
> +			return errors.New("unexpected value type for counter metric")
`unexpected value type` можно залогировать

2023-12-20 22:59 UTC, s-shpak commented on internal/server/storage/memstorage.go
> +	Data sync.Map
Не стоит делать это поле экспортируемым, оно должно быть инкапсулировано

2023-12-21 11:40 UTC, ElizavetaFirst commented on cmd/server/root/root.go
> +					fmt.Printf("failed to close the postgres storage %v", err)
У меня логгер инициализируется в webserver.go:
r.Use(logger.InitLogger())
как его использовать снаружи?
Значит ли это, что инициализировать его нужно в root.go?

2023-12-24 16:53 UTC, s-shpak commented on cmd/server/root/root.go
> +					fmt.Printf("failed to close the postgres storage %v", err)
Да, логгер как правило инициализируют в самом начале выполнения программы

2023-12-24 16:55 UTC, s-shpak requested changes
См. незакрытые комментарии

2023-12-26 19:28 UTC, ElizavetaFirst commented on internal/server/handler/handler.go
> +	value, err := h.Storage.Get(c, &storage.GetOptions{
такую и возвращали,только не проверяли, проверку добавила

2023-12-26 20:01 UTC, ElizavetaFirst commented on internal/server/db/db.go
> +	return nil // pgxpool.Pool не нужно закрывать
Вроде как пул соединений должен обеспечить закрытие всех соединений, но на всякий случай добавила явный Close()

2023-12-29 09:17 UTC, s-shpak requested changes

2023-12-29 09:17 UTC, s-shpak commented on cmd/server/main.go
>  		fmt.Println(err)
```suggestion
		log.Println(err)
```

2023-12-29 09:17 UTC, s-shpak commented on internal/server/saver/saver.go
>  			os.Exit(0)
Здесь ты завершаешься из горутины

2023-12-29 09:17 UTC, s-shpak commented on internal/agent/uploader/uploader.go
> +			Value: &v,
Не сделано

2023-12-29 09:17 UTC, s-shpak commented on internal/server/db/db.go
> +	return nil // pgxpool.Pool не нужно закрывать
Да, но сам пул соединений надо закрыть, чтобы он закрыл соединения, которыми он управляет. Этот коммент можно зарезолвить

2023-12-29 09:17 UTC, s-shpak commented on internal/server/handler/handler.go
>  		c.Status(http.StatusNotFound)
У тебя в коде есть еще несколько мест, где ты возвращаешь `StatusNotFound`, и которые тоже стоит обработать таким образом

2023-12-29 09:17 UTC, s-shpak commented on internal/server/handler/handler.go
>  		fmt.Println(reflect.TypeOf(value.Value).Kind() == reflect.Int64)
deadcode

2023-12-29 09:17 UTC, s-shpak commented on internal/server/storage/dbstorage.go
> +	if opts.Update.Type == constants.Counter {
Здесь также тип может быть не Counter, и не Gauge

2023-12-29 09:17 UTC, s-shpak commented on internal/server/handler/handler.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
У тебя в коде есть и другие места с такой же проблемой

2023-12-29 09:17 UTC, s-shpak commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
Не сделано

2023-12-29 09:17 UTC, s-shpak commented on internal/server/storage/memstorage.go
> +			return errors.New("unexpected value type for counter metric")
Я имел в виду другое: его можно поместить в тело ошибки, которая выше будет залогирована

2023-12-29 09:17 UTC, s-shpak commented on cmd/server/root/root.go
> +		ctx := context.WithValue(context.Background(), constants.LoggerKey{}, log)
В целом, передавать логгер внутри контекста - не лучшая практика: его можно прокидывать туда, где он нужен явно. Если будет интересно почему, можем обсудить.

2023-12-29 09:17 UTC, s-shpak commented on internal/constants/constants.go
> +type LoggerKey struct{}
Лучше использовать `iota` и новый тип для этого. На одном из вебинаров это обсуждали (посмотри код вебинаров, чтобы понять где и как)

2023-12-29 09:17 UTC, s-shpak commented on internal/server/handler/handler.go
> +		c.Request.Context().Value(constants.LoggerKey{}).(*zap.Logger).Error("ShouldBindJSON return error",
При извлечении значения их контекста необходимо:
- проверить, что оно вообще там есть
- проверить его тип

2023-12-29 09:17 UTC, s-shpak commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
Это не сделано

2023-12-29 09:44 UTC, ElizavetaFirst commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
"Graceful shutdown пока делать не обязательно" - не стала резолвить комменты, в которых написано, что их резолвить необязательно)
если все-таки их надо резолвить,пожалуйста, пишите об этом прямо)

2024-01-03 11:23 UTC, ElizavetaFirst commented on internal/server/handler/handler.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
не нахожу, подскажи пожалуйста, где именно?

2024-01-05 13:21 UTC, ElizavetaFirst commented on cmd/server/main.go
>  		fmt.Println(err)
логгер создается внутри RunE, тут его не вызвать

2024-01-06 10:25 UTC, ElizavetaFirst commented on cmd/server/root/root.go
> +		ctx := context.WithValue(context.Background(), constants.LoggerKey{}, log)
вроде бы ты говорил, что держать что-то в контексте плохо, потому что оно может быть любого типа и не только того, которого мы ожидаем

2024-01-06 11:08 UTC, ElizavetaFirst commented on internal/agent/uploader/uploader.go
> +			Value: &v,
В условиях задачи они должны быть указателями, потому и тут -указатели - сразу их в сруктуру анмаршаллю и использую

2024-01-09 16:25 UTC, s-shpak commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
Ок, понял проблему: если ты решаешь не делать что-то, то пиши, пожалуйста, в комменте об этом. Этот коммент можно зарезолвить

2024-01-09 16:26 UTC, s-shpak commented on internal/server/handler/handler.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
Возможно, я смотрел старую версию, сорри

2024-01-09 16:28 UTC, s-shpak commented on cmd/server/main.go
>  		fmt.Println(err)
Да, поэтому я предлагаю просто использовать стандартный логгер вместо `fmt`: использовать `fmt` для логгирования считается плохой практикой

2024-01-09 16:32 UTC, s-shpak commented on cmd/server/root/root.go
> +		ctx := context.WithValue(context.Background(), constants.LoggerKey{}, log)
да, и кроме того, логгер - явная зависимость компонента, лучше не прятать ее

2024-01-09 16:43 UTC, s-shpak requested changes
См. проблему с `fmt`

2024-01-10 15:41 UTC, ElizavetaFirst commented on internal/server/saver/saver.go
>  	c := make(chan os.Signal, 1)
а я тут сделала кстати какую-то версию graceful shutdown в итоге)

2024-01-11 15:31 UTC, s-shpak approved these changes

2024-01-12 14:29 UTC, merged