Iter9
ElizavetaFirst/go-metrics-alerts pull request #8
Opened 2023-11-30 20:26 UTC by ElizavetaFirst

2023-12-01 08:04 UTC, arttet requested changes
Please add the codecov report
https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

2023-12-01 08:04 UTC, arttet commented on internal/agent/uploader/uploader.go
> +func (u *Uploader) sendMetricsJSON(url string, metrics metrics.Metrics) error {
It seems this function should work with data as bytes

2023-12-01 08:04 UTC, arttet commented on internal/agent/uploader/uploader.go
> +func (u *Uploader) sendMetricsJSON(url string, metrics metrics.Metrics) error {
```suggestion
func (u *Uploader) sendMetricsJSON(url string, metrics []byte) error {
```

2023-12-01 08:04 UTC, arttet commented on internal/agent/uploader/uploader.go
> +	switch resp.Header.Get("Content-Encoding") {
It would be better if it is in a middleware

2023-12-01 08:04 UTC, arttet commented on internal/logger/logger.go
> +		if err := log.Sync(); err != nil && (!errors.Is(err, syscall.EBADF) && !errors.Is(err, syscall.ENOTTY)) {
```suggestion
		if err := log.Sync(); err != nil {
```

2023-12-01 08:04 UTC, arttet commented on internal/logger/logger.go
> +		if err := log.Sync(); err != nil && (!errors.Is(err, syscall.EBADF) && !errors.Is(err, syscall.ENOTTY)) {
Why do you need it?

2023-12-03 13:06 UTC, ElizavetaFirst commented on internal/logger/logger.go
> +		if err := log.Sync(); err != nil && (!errors.Is(err, syscall.EBADF) && !errors.Is(err, syscall.ENOTTY)) {
https://github.com/uber-go/zap/issues/328
проблема zap sync  на маке, но если не паниковать,то можно и без этого обойтись)

2023-12-03 14:15 UTC, closed without merging